version: '3'

services:
  # PySpark Service
  pyspark:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
    container_name: pyspark_project2
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888" # Jupyter Notebook UI
      - "4040:4040" # Spark UI
    volumes:
      - "./src/:/home/jovyan/"
      - "./data:/home/jovyan/data"
    depends_on:
      - kafka  # Ensure Kafka is started before PySpark

  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
